---
# build_kali_desktop/tasks/tools-c2-sliver.yml

# The latest sliver version is available in Kali's apt repo, however it doesn't configure the system service.
# This task will use the installer script from the sliver GitHub for now. This is the same file you get from https://sliver.sh/install.

# ===========
# apt Install
# ===========
#
# - name: Ensure dependancies are installed
#   ansible.builtin.apt:
#     pkg:
#       - git
#       - mingw-w64
#     state: present
#   become: true
#   become_method: ansible.builtin.sudo
#
# - name: Install Sliver C2 (apt)
#   ansible.builtin.apt:
#     name: sliver
#     state: present
#     update_cache: true
#   become: true
#   become_method: ansible.builtin.sudo

# ==============
# Script Install
# ==============

# This is the same file you get from https://sliver.sh/install
# Fails if the checksum of the installer has changed, so you can review before running it
# `ignore_errors: true` allows builds to safely skip this task
- name: Download Sliver C2 installer script
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/BishopFox/sliver/master/docs/sliver-docs/public/install
    dest: "{{ tools_path }}/sliver-installer.sh"
    mode: "0750"
    checksum: "sha256:{{ sliver_installer_sha256 }}"
  register: sliver_download
  ignore_errors: true

- name: Set SHA256SUM result of sliver-installer.sh
  ansible.builtin.set_fact:
    sliver_checksum_ok: "{{ sliver_download is not failed }}"

- name: Alert on checksum failure
  ansible.builtin.debug:
    msg: |
      [*]CHECKSUM MISMATCH
      The task to install Sliver will be skipped.
      Review https://github.com/BishopFox/sliver/blob/master/docs/sliver-docs/public/install for changes first.
  when: not sliver_checksum_ok

- name: Populate service facts
  ansible.builtin.service_facts:

# Ensures we only run the installer if checksum is valid and service doesn't exist
- name: Install Sliver C2 (script)
  ansible.builtin.command: "{{ tools_path }}/sliver-installer.sh"
  when:
    - sliver_checksum_ok
    - ansible_facts.services['sliver.service'] is not defined
  become: true
  become_method: ansible.builtin.sudo

# This means sliver can only be accessed locally or via ssh port forwarding
- name: Set Sliver daemon to only listen on localhost
  ansible.builtin.lineinfile:
    path: /root/.sliver/configs/server.json
    search_string: '"host": "",'
    line: '        "host": "127.0.0.1",'
    owner: root
    group: root
    mode: "0600"
  when:
    - sliver_checksum_ok
    - ansible_facts.services['sliver.service'] is defined
  become: true
  become_method: ansible.builtin.sudo

# Also restarts the service so it's only listening on localhost
- name: Enable Sliver service on startup
  ansible.builtin.service:
    name: sliver
    state: restarted
    enabled: true
  when:
    - sliver_checksum_ok
    - ansible_facts.services['sliver.service'] is defined
  become: true
  become_method: ansible.builtin.sudo
